version: "3.7"
services:
  app:
    build:
      args:
        user: sondos
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: 4sale-php
    tty: true
    container_name: 4sale-php
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - $HOME/.composer/:$HOME/.composer/
    networks:
      - laravel
  db:
    image: mysql:8.0
    container_name: db-4sale
    restart: unless-stopped
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - laravel
  nginx:
    image: nginx:alpine
    container_name: 4sale-nginx
    restart: unless-stopped
    ports:
      - 8001:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - laravel
networks:
  laravel:
    driver: bridge
