version: '3.8'

services:

  # Web Server Service
  nginx:
    image: nginx:alpine
    container_name: 4sale-nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx/conf.d/:/etc/nginx/conf.d/
    tty: true
    depends_on:
      - app
      - db

  #Database Service
  db:
    image : mysql
    container_name : db-4sale
    volumes:
      - ./docker-compose/mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USERNAME=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}

  # Application Service
  app:
    container_name: 4sale-php
    image: 4sale-php
    build: 
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    ports:
      - "9000:9000"
    working_dir: /var/www
